// src/views/forge.tsx
import React, { useState } from 'react';
import Pixel from 'src/elements/pixel';
import { BLACK, colorInfo, rndColorIdx } from 'src/helpers/color-utils';
import Plate, { DIMENSION } from '../elements/plate';

function Forge({}) {
  const [pixels, setPixels] = useState<number[][]>(Array(DIMENSION ** 2).fill([BLACK]));

  const [pixelIdx, setPixelIdx] = useState(0);
  const [avlbPixels, setAvlbPixels] = useState(
    Array(DIMENSION * 2)
      .fill(1)
      .map(() => [rndColorIdx(), rndColorIdx()])
  );

  const usePixel = (pixel: number[], idx: number) => {
    setPixelIdx(idx);
  };

  const applyPixel = (idx: number) => {
    if (avlbPixels.length === 0) {
      return;
    }
    const s = [...pixels];
    s[idx] = [...avlbPixels[pixelIdx]];
    setPixels(s);
    const apx = [...avlbPixels];
    apx.splice(pixelIdx, 1);
    setAvlbPixels(apx);
    setPixelIdx(0);
  };

  return (
    <div className="absolute w-full h-full grid grid-cols-[14rem,4fr] gap-4">
      <div className="border-2 border-pink-500 overflow-y-scroll space-y-2 py-2">
        {avlbPixels.map((p, i) => (
          <div
            key={i}
            className={
              'border-2  mx-2 flex items-center cursor-pointer ' +
              (pixelIdx === i ? 'bg-pink-500 border-pink-500 text-white' : 'bg-pink-300 border-pink-300 text-pink-600')
            }
            onClick={() => usePixel(p, i)}
          >
            <Pixel className="h-12 w-12" colors={p} />
            <div className={'grid text-base grow ' + (p.length > 1 ? 'grid-cols-2' : 'grid-cols-1')}>
              {p.map((color, ic) => (
                <span className="text-center" key={ic}>
                  {colorInfo(color)[1]}
                </span>
              ))}
            </div>
          </div>
        ))}
      </div>
      <div className="border-2 border-pink-500 grid m-auto aspect-square h-full cursor-pointer">
        <div className="col-[1] row-[1] grid">
          <Plate pixels={pixels} />
        </div>
        <div
          className="col-[1] row-[1] grid gap-[1px]"
          style={{
            gridTemplateRows: `repeat(${DIMENSION}, 1fr)`,
            gridTemplateColumns: `repeat(${DIMENSION}, 1fr)`
          }}
        >
          {pixels.map((_, i) => (
            <div key={i} className="opacity-0" onClick={() => applyPixel(i)}></div>
          ))}
        </div>
      </div>
    </div>
  );
}

export default Forge;

// src/routes/Forge.tsx
import { Component, createSignal, Index } from 'solid-js';
import { Portal } from 'solid-js/web';
import Button from '../elements/Button';
import Pixel, { PixelData } from '../elements/Pixel';
import { DIMENSION } from '../elements/plate';
import { BLACK, rndColorIdx } from '../helpers/color-utils';

const Forge: Component = () => {
  const [availablePixels, setAvailablePixels] = createSignal<PixelData[]>(Array(DIMENSION * 2)
    .fill(1)
    .map(() => [rndColorIdx(), rndColorIdx(), rndColorIdx(), rndColorIdx()]));

  const [pixels, setPixels] = createSignal<PixelData[]>(Array(DIMENSION ** 2).fill(1)
    .map(() => [BLACK]));

  const [draggingPixel, setDraggingPixel] = createSignal<{ idx: number; pixel: PixelData }>();
  let draggablePixel: HTMLDivElement;
  const movePixel = (e: MouseEvent) => {
    draggablePixel.style.setProperty('left', `${e.x - 22}px`);
    draggablePixel.style.setProperty('top', `${e.y - 22}px`);
  };

  const drag = (data: { idx: number, pixel: PixelData }, e: MouseEvent) => {
    document.body.style.setProperty('cursor', 'grabbing');
    document.addEventListener('mousemove', movePixel);
    movePixel(e);
    setDraggingPixel(data);
  };

  const drop = (idx: number) => {
    document.body.style.setProperty('cursor', 'unset');
    document.removeEventListener('mousemove', movePixel);

    const s = [...pixels()];
    const dp = draggingPixel();
    if (s[idx][0] === BLACK && !dp) return;

    const apx = [...availablePixels()];
    if (dp) {
      apx.splice(dp.idx, 1);
    } else {
      apx.unshift(s[idx]);
    }
    setAvailablePixels(apx);

    s[idx] = [...dp?.pixel || [BLACK]];
    setDraggingPixel(undefined);
    setPixels(s);
  };

  return <div className='flex flex-col-reverse sm:flex-row-reverse text-white'>
    {/* Pixels */}
    {/* TODO: rework this with grid */}
    <div className='m-auto sm:ml-8 overflow-x-scroll sm:overflow-y-scroll sm:overflow-x-hidden
                    min-w-[100vw] sm:min-h-[80vh] max-h-[80vh] sm:min-w-0 max-w-[100vw]
      p-2 bg-pink-500/70 flex sm:flex-col'>
      <Button className='sticky -left-2 sm:-top-2 text-sm'>Filter</Button>
      <div className='bg-black/70'>
        <div className='bg-pink-500/20 p-2'>
          <div className='grid grid-flow-col sm:grid-flow-row select-none space-x-2 sm:space-x-0 sm:space-y-2'>
            {/* This could/should be optimized with a virtual list; or something that pauses the animation of pixels */}
            <Index each={availablePixels()}>
              {(p, i) =>
                <Pixel className="h-12 w-12 cursor-grab"
                  colors={p()} onMouseDown={[drag, { idx: i, pixel: p() }]} />
              }
            </Index>
          </div>
        </div>
      </div>
    </div>
    {/* Draggable Pixel */}
    <Portal mount={document.getElementById('root')!}>
      <Pixel ref={r => draggablePixel = r}
        className={`h-12 w-12 z-10 absolute pointer-events-none  ${draggingPixel() ? '' : 'hidden'}`}
        colors={draggingPixel()?.pixel || [BLACK]} />
    </Portal>

    {/* Plate */}
    <div className='bg-pink-500/70 p-2 aspect-square m-auto mr-0 grow grid
                    max-h-[100vw] max-w-[100vw] sm:max-h-[80vh] sm:max-w-[80vh]'>
      <div className='bg-white grid'
        style={{
          'grid-template-rows': `repeat(${DIMENSION}, 1fr)`,
          'grid-template-columns': `repeat(${DIMENSION}, 1fr)`
        }}>
        <Index each={pixels()}>
          {(p, i) => <Pixel className='hover:opacity-40' colors={p()} onMouseUp={[drop, i]} />}
        </Index>
      </div>
    </div>
  </div>;
};

export default Forge;
